### ISSUE TITLE
ESConnection. isClosed() check error

### ISSUE THREAD

**Issue by seongjookim** [Anchormen/sql4es#1]
If I use sql4es driver in apache-comon-dhcp library, Connection initialization error occurs as follows 
"initializeConnection: connection closed"
The isClosed () method of ESConnection class may need to be modified as follows:
public boolean isClosed() throws SQLException {
	return !active;  // old version <-- active
}

**Comment by corneversloot** [comment]
hi seongjookim, congratulations you are the first to open an issue for the driver :). Thanks for reporting this bug. Apparently none of the clients I use perform this check upon connection initialization. I have fixed it according to your suggestion.
