### ISSUE TITLE
Any plan for "Parent-Child" search on sql4es?

### ISSUE THREAD

**Issue by yangfeiran** [Anchormen/sql4es#14]
Hi,

I think I share the same preference with you guys, I think use SQL to search for result is much more convenient than use JSON or java client to query from Elasticsearch.

However, the question I have here is that does sql4es plan to support "Parent-Child" search on Elasticsearch? I think the "Parent-Child" search is quite a major feature for Elasticsearch. Hopefully sql4es can added this to the future milestone.

Sincerely,

Feiran

**Comment by corneversloot** [comment]
Hi Feiran,

I remember looking into the parent-child relation a while ago but unfortunately im not planning on adding it any time soon due to lack of time. It would be great if someone else would add it ... :)

Cheers,
Corné

**Comment by yangfeiran** [comment]
@corneversloot Alright, cheers!
