### ISSUE TITLE
getDate(int columnIndex, Calendar cal) not implemented

### ISSUE THREAD

**Issue by dmarkhas** [Anchormen/sql4es#23]
The getDate function that accepts a column index and a calendar is not implemented:

```
	@Override
	public Date getDate(int columnIndex, Calendar cal) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}
```

Some clients (Apache Drill being one) require this functionality since they always pass a Calendar object.

**Comment by dmarkhas** [comment]
I noticed that you already added it as a simple wrapper around getDate - I think it is sufficient, the JDBC spec doesn't specify what getDate(int, Calendar) should do differently, just that it should return a Date object. 
The Oracle JDBC for example only uses the calendar to construct the milliseconds value of the Date object (https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html) which I think is redundant.

Anyway, I have tested the latest release and it is working as expected, so I think you can go ahead and close this issue :-)

**Comment by corneversloot** [comment]
I was still thinking about it and wanted to validate if ES always provides a timezone in its Date's. But ill leave it for now
