### ISSUE TITLE
Any support for 2.4.3?

### ISSUE THREAD

**Issue by iommi1** [Anchormen/sql4es#28]
Let me say this project is awesome!

It works for me when I connect to 2.4.0 but get a transport error when i connect to 2.4.3. Is it supported?

**Comment by corneversloot** [comment]
Thanks for the kind words :)

I have updated the master branch to elasticsearch 2.4.3 and put the new 0.8.2.4 build in the releases directory. Please see if that one works.

**Comment by iommi1** [comment]
Thanks, looks like it working fine!
