### ISSUE TITLE
how to get all types in one index?

### ISSUE THREAD

**Issue by weishishuo** [Anchormen/sql4es#29]
how to get all types in one index?
i want to do a query like "show tables" in sql

**Comment by corneversloot** [comment]
You have to create an Elasticsearch alias containing the indices (and hence their types) you want. Then you can connect to the alias in the same way as you would connect to an index and list the tables to view all types.

Visit https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html to learn about aliases.
