### ISSUE TITLE
mysql Load Balancing jdbc url style

### ISSUE THREAD

**Issue by firesprite** [Anchormen/sql4es#5]
hi. very thanks

i wanted a mysql Load Balancing jdbc url style setting
So I modify the source code

-- ESDriver.java
package nl.anchormen.sql4es.jdbc;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.DriverPropertyInfo;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import nl.anchormen.sql4es.model.HostPortPair;
import nl.anchormen.sql4es.model.Utils;

/**
 * Basic {@link Driver} implementation used to get {@link ESConnection}.
 * 
 * @author cversloot
 *
 */
public class ESDriver implements Driver{

	private static final Logger logger = LoggerFactory.getLogger(ESDriver.class.getName());
	
	private static final String ES_HOSTS = "es.hosts";
	private static final String ES_INDEX = "es.index";
	
	/**
	 * Register this driver with the driver manager
	 */
	static{
		try {
			DriverManager.registerDriver(new ESDriver());
		} catch (SQLException sqle) {
			logger.error("Unable to register Driver", sqle);
		}
	}
	
//	@Override
//	public Connection connect(String url, Properties info) throws SQLException {
//		Object[] conInfo = parseURL(url, info);
//		String host = (String)conInfo[0];
//		int port = (int)conInfo[1];
//		String index = (String)conInfo[2];
//		Properties props = (Properties)conInfo[3];
//		return new ESConnection(host, port, index, props);
//	}
	
	@Override
	public Connection connect(String url, Properties info) throws SQLException {
		Properties properties = parseURL(url, info);

		String hosts = (String)properties.getProperty(ES_HOSTS);
		String index = (String)properties.getProperty(ES_INDEX);
		ConnectionInfo connInfo = new ConnectionInfo(hosts, index, properties);
		return new ESConnection(connInfo);
	}
	
//	/**
//	 * Parses the url and returns information required to create a connection. Properties
//	 * in the url are added to the provided properties and returned in the object array
//	 * @param url
//	 * @param info
//	 * @return {String:host, int:port, String:index, Properties:info}
//	 * @throws SQLException
//	 */
//	private Object[] parseURL(String url, Properties info) throws SQLException{
//		if(!acceptsURL2(url)) 
//			throw new SQLException("Invalid url");
//		try {
//			URI uri = new URI(url.substring(12));
//			String host = uri.getHost();
//			int port = (uri.getPort() < 0 ? Utils.PORT : uri.getPort());
//			String index = uri.getPath().length() <= 1 ? null : uri.getPath().split("/")[1];
//			Properties props = Utils.defaultProps();
//			if(info != null) {
//				props.putAll(info);
//			}
//			info = props;
//			if(uri.getQuery() != null) 
//				for(String keyValue : uri.getQuery().split("&")){
//					String[] parts = keyValue.split("=");
//					if(parts.length > 1) info.setProperty(parts[0].trim(), parts[1].trim());
//					else info.setProperty(parts[0], "");
//				}
//			return new Object[]{host, port, index, info};
//		} catch (URISyntaxException e) {
//			throw new SQLException("Unable to parse URL. Pleas use '"+Utils.PREFIX+"//host:port/schema?{0,1}(param=value&)*'", e);
//		}catch(ArrayIndexOutOfBoundsException e){
//			throw new SQLException("No shema (index) specified. Pleas use '"+Utils.PREFIX+"//host:port/schema?{0,1}(param=value&)*'");
//		}catch(Exception e){
//			throw new SQLException("Unable to connect to database due to: "+e.getClass().getName(), e);
//		}
//	}

	private Properties parseURL(String url, Properties defaults) throws SQLException 
	{
		if(url == null || !url.toLowerCase().startsWith(Utils.PREFIX)) 
			return null;
		
		Properties urlProps = (defaults != null) ? new Properties(defaults) : new Properties();
		
		int beginningOfSlashes = url.indexOf("//");
		int questionIndex = url.indexOf("?");
		String queryString = (questionIndex > 1)? url.substring(questionIndex + 1).trim(): "";
		//jdbc:sql4es remove
		url = (questionIndex > 0)? 
				url.substring(beginningOfSlashes + 2, questionIndex) 
				: url.substring(beginningOfSlashes + 2);
		
		//  host:port,host2,host3:port/index?cluster.name=clustername
		String[] split = url.split("/", 3);
		if(split.length > 2)
		{
			throw new SQLException("Unable to parse URL. Pleas use '"+Utils.PREFIX+"//host:port[,host:port]*/schema?(param=value&)*'");
		}else 
		{
			if(split.length == 1 // host:port,host2,host3:port?cluster.name=clustername
					|| split[1].trim().isEmpty()) //host:port,host2,host3:port/?cluster.name=clustername
			{
				// host:port,host2,host3:port?cluster.name=clustername
				throw new SQLException("No shema (index) specified. Pleas use '"+Utils.PREFIX+"//host:port[,host:port]*/schema?(param=value&)*'");
			}
		}
		String hostOrPortPair = split[0];
		// add property : es.hosts
		if(!urlProps.containsKey(ES_HOSTS))
		{
			urlProps.setProperty(ES_HOSTS, hostOrPortPair);
		}else
		{
			String esHosts = urlProps.getProperty(ES_HOSTS).trim();
			if(esHosts.isEmpty())
			{
				urlProps.setProperty(ES_HOSTS, hostOrPortPair);
			}else
			{
				urlProps.setProperty(ES_HOSTS, esHosts+","+hostOrPortPair);
			}
		}
		
		//add property : es.index
		String index = split[1];
		urlProps.setProperty(ES_INDEX, index);
		if(!queryString.isEmpty())
		{
			String[] querys = queryString.split("&");
			for (String pair : querys)
			{
				int idx = pair.indexOf("=");
				try
				{
					urlProps.put(URLDecoder.decode(pair.substring(0, idx), "UTF-8"), URLDecoder.decode(pair.substring(idx + 1), "UTF-8"));
				} catch (UnsupportedEncodingException e)
				{
					try
					{
						urlProps.put(URLDecoder.decode(pair.substring(0, idx), Charset.defaultCharset().name()), 
								URLDecoder.decode(pair.substring(idx + 1), Charset.defaultCharset().name()));
					} catch (UnsupportedEncodingException e1)
					{
						throw new SQLException("Unable to connect to database due to: "+e.getClass().getName(), e);
					}
				}	
			}
		}
		
		return urlProps;
	}
	
	
//	@Override
//	public boolean acceptsURL(String url) throws SQLException {
//		if(!url.toLowerCase().startsWith(Utils.PREFIX)) return false;
//		try {
//			URI uri = new URI(url.substring(5));
//			if(uri.getHost() == null) throw new SQLException("Invalid URL, no host specified");
//			if(uri.getPath() == null) throw new SQLException("Invalid URL, no index specified");
//			if(uri.getPath().split("/").length > 2) throw new SQLException("Invalid URL, "+uri.getPath()+" is not a valid index");
//		} catch (URISyntaxException e) {
//			throw new SQLException("Unable to parse URL", e);
//		}
//		return true;
//	}

	@Override
	public boolean acceptsURL(String url) throws SQLException 
	{
		return (parseURL(url, null) != null);
	}
	
	@Override
	public DriverPropertyInfo[] getPropertyInfo(String url, Properties info) throws SQLException {
		Properties props = (Properties)parseURL(url, info);
		Properties defaultProps = Utils.defaultProps();
		
		DriverPropertyInfo[] result = new DriverPropertyInfo[defaultProps.size() + 2];
		result[0] = new DriverPropertyInfo(ES_HOSTS, (String) props.get(ES_HOSTS));
		result[0].required = true;
		result[0].description = "elasticsearch transport address list";
		result[1] = new DriverPropertyInfo(ES_INDEX, (String) props.get(ES_INDEX));
		result[1].required = true;
		result[1].description = "elasticsearch index name";
		
		result[2] = new DriverPropertyInfo("cluster.name", (String) props.get("cluster.name"));
		result[2].required = false;
		result[2].description = "If your clustername is not 'elasticsearch' you should specify the clustername";
		
		int index = 3;
		for(Object key : defaultProps.keySet()){
			result[index] = new DriverPropertyInfo((String)key, props.get(key).toString());
			index++;
		}
		return result;
	}
	
//	@Override
//	public DriverPropertyInfo[] getPropertyInfo(String url, Properties info) throws SQLException {
//		Properties props = (Properties)parseURL(url, info)[3];
//		DriverPropertyInfo[] result = new DriverPropertyInfo[props.size()];
//		int index = 0;
//		for(Object key : props.keySet()){
//			result[index] = new DriverPropertyInfo((String)key, props.get(key).toString());
//			index++;
//		}
//		return result;
//	}

	@Override
	public int getMajorVersion() {
		return Utils.ES_MAJOR_VERSION;
	}

	@Override
	public int getMinorVersion() {
		return Utils.ES_MINOR_VERSION;
	}

	@Override
	public boolean jdbcCompliant() {
		return false;
	}

	@Override
	public java.util.logging.Logger getParentLogger() throws SQLFeatureNotSupportedException {
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	/**
	 * The Class Connection Info.
	 */
	public static class ConnectionInfo
	{
		private List<HostPortPair> hosts = new ArrayList<HostPortPair>(3);
		
		private String index;
		
		private Properties properties;
		
		public ConnectionInfo(String host, int port, String index, Properties properties) throws SQLException
		{
			this(index, properties);
			this.addHost(new HostPortPair(host, port));
		}
		
		public ConnectionInfo(String hostAndPortPairs, String index, Properties properties) throws SQLException
		{
			this(index, properties);
			this.addHost(hostAndPortPairs);
		}

		public ConnectionInfo(HostPortPair hostPortPair, String index, Properties properties) throws SQLException
		{
			this(index, properties);
			this.addHost(hostPortPair);
		}

		public ConnectionInfo(List<HostPortPair> hostPortPairs, String index, Properties properties) throws SQLException
		{
			this(index, properties);
			for (HostPortPair hostPortPair : hostPortPairs)
			{
				this.addHost(hostPortPair);
			}
		}
		
		private ConnectionInfo(String index, Properties properties) throws SQLException
		{
			this.setIndex(index);
			String esHosts = properties.getProperty(ES_HOSTS);
			if(esHosts != null)
			{
				this.addHost(esHosts);
			}
			this.setProperties(properties);
		}

		public List<HostPortPair> getHosts()
		{
			return hosts;
		}
		
		
		public boolean addHost(HostPortPair hostPortPair)
		{
			for (HostPortPair host : hosts)
			{
				if(host.equals(hostPortPair))
				{
					return false;
				}
			}
			this.hosts.add(hostPortPair);
			return true;
		}
		
		private void addHost(String hostAndPortPairs) throws SQLException
		{
			for (String hostPort : hostAndPortPairs.split(","))
			{
				String[] _hostPort = hostPort.split(":");
				String host = _hostPort[0].trim();
				HostPortPair hostPair =  (_hostPort.length > 1) ? new HostPortPair(host, Integer.parseInt(_hostPort[1])) : new HostPortPair(host); 
				this.addHost(hostPair);
			}
		}
		
		public String getIndex()
		{
			return index;
		}
		
		/**
		 * @param index the index to set
		 * @throws SQLException 
		 */
		public void setIndex(String index) throws SQLException
		{
			if(index == null || index.isEmpty())
			{
				throw new SQLException("Invalid URL, no index specified");
			}
			this.index = index;
		}
		
		public Properties getProperties()
		{
			return properties;
		}
		
		public void setProperties(Properties properties)
		{
			if(this.properties == null)
			{
				this.properties = new Properties();
			}
			this.properties.putAll(properties);
		}
		
		public String toString()
		{
			StringBuilder tmp = new StringBuilder();
			tmp.append(Utils.PREFIX);
			tmp.append("//");
			for (HostPortPair hostPortPair : hosts)
			{
				tmp.append(hostPortPair.toString());
				tmp.append(',');
			}
			tmp.delete(tmp.length()-1, tmp.length());
			tmp.append('/');
			tmp.append(index);
			if(properties.size() > 0)
			{
				tmp.append('?');
				for (Object key : properties.entrySet())
				{
					tmp.append(key);
					tmp.append('=');
					tmp.append(properties.getProperty((String) key));
					tmp.append('&');
				}
				tmp.delete(tmp.length()-1, tmp.length());
			}
			return tmp.toString();
		}
	}
}

---- ESConnection.java
package nl.anchormen.sql4es.jdbc;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

import org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest;
import org.elasticsearch.client.Client;
import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.transport.InetSocketTransportAddress;
import org.elasticsearch.test.ESIntegTestCase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import nl.anchormen.sql4es.ESDatabaseMetaData;
import nl.anchormen.sql4es.jdbc.ESDriver.ConnectionInfo;
import nl.anchormen.sql4es.model.Heading;
import nl.anchormen.sql4es.model.HostPortPair;
import nl.anchormen.sql4es.model.Utils;

/**
 * A {@link Connection} implementation effectively wrapping an Elasticsearch
 * {@link Client}.
 * 
 * @author cversloot
 *
 */
public class ESConnection implements Connection
{

//	private String host;
//	private int port;
//	private String index;
//	private Properties props;
	
	private ConnectionInfo connInfo;

	private Client client;
	private boolean active = true;
	private int timeout = Integer.MAX_VALUE;

	private final Logger logger = LoggerFactory.getLogger(this.getClass());
	private boolean autoCommit = false;
	private boolean readOnly = true;
	private List<ESStatement> statements = new ArrayList<ESStatement>();
	

	/**
	 * Builds the es {@link Client} using the provided parameters.
	 * 
	 * @param host
	 * @param port
	 * @param index
	 * @param props
	 *            the properties will all be copied to the Settings.Builder used
	 *            to create the Client
	 * @throws SQLException
	 */
	public ESConnection(String host, int port, String index, Properties props) throws SQLException
	{
		this(new ConnectionInfo(host, port, index, props));
	}

	public ESConnection(ConnectionInfo connectionInfo) throws SQLException
	{
		this.connInfo = connectionInfo;
		this.client = buildClient();
		try
		{
			this.getTypeMap(); // loads types into properties
		} catch (Exception e)
		{
			throw new SQLException("Unable to connect to specified elasticsearch host(s)", e);
		}
	}
	
	
//	/**
//	 * Builds the Elasticsearch client using the properties this connection was
//	 * instantiated with
//	 * 
//	 * @return
//	 * @throws SQLException
//	 */
//	private Client buildClient() throws SQLException
//	{
//		if (props.containsKey("test"))
//		{ // used for integration tests
//			return ESIntegTestCase.client();
//		} else
//		{
//			try
//			{
//				Settings.Builder settingsBuilder = Settings.settingsBuilder();
//				for (Object key : this.props.keySet())
//				{
//					settingsBuilder.put(key, this.props.get(key));
//				}
//				Settings settings = settingsBuilder.build();
//				TransportClient client = TransportClient.builder().settings(settings).build()
//						.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(host), port));
//
//				// add additional hosts if set in URL query part
//				if (this.props.containsKey("es.hosts"))
//					for (String hostPort : this.props.getProperty("es.hosts").split(","))
//					{
//						String newHost = hostPort.split(":")[0].trim();
//						int newPort = (hostPort.split(":").length > 1 ? Integer.parseInt(hostPort.split(":")[1])
//								: Utils.PORT);
//						client.addTransportAddress(
//								new InetSocketTransportAddress(InetAddress.getByName(newHost), newPort));
//						logger.info("Adding additional ES host: " + hostPort);
//					}
//
//				// check if index exists
//				if (index != null)
//				{
//					boolean indexExists = client.admin().indices().exists(new IndicesExistsRequest(index)).actionGet()
//							.isExists();
//					if (!indexExists)
//						throw new SQLException("Index or Alias '" + index + "' does not exist");
//				}
//				return client;
//			} catch (UnknownHostException e)
//			{
//				throw new SQLException("Unable to connect to " + host, e);
//			} catch (Throwable t)
//			{
//				throw new SQLException("Unable to connect to database", t);
//			}
//		}
//	}

	private Client buildClient() throws SQLException
	{
		Properties props = connInfo.getProperties();
		if (props.containsKey("test"))
		{ // used for integration tests
			return ESIntegTestCase.client();
		} else
		{
			try
			{
				Settings.Builder settingsBuilder = Settings.settingsBuilder();
				for (Object key : props.keySet())
				{
					settingsBuilder.put(key, props.get(key));
				}
				Settings settings = settingsBuilder.build();
				TransportClient client = TransportClient.builder().settings(settings).build();

				List<HostPortPair> hosts = connInfo.getHosts();
				for (HostPortPair host : hosts)
				{
					client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(host.getHost()), host.getPort()));
					logger.info("Adding additional ES host: " + host);
				}

				// check if index exists
				if (connInfo.getIndex() != null)
				{
					boolean indexExists = client.admin().indices().exists(new IndicesExistsRequest(connInfo.getIndex())).actionGet()
							.isExists();
					if (!indexExists)
						throw new SQLException("Index or Alias '" + connInfo.getIndex() + "' does not exist");
				}
				return client;
			} catch (UnknownHostException e)
			{
				throw new SQLException("Unable to connect to " + connInfo.getHosts(), e);
			} catch (Throwable t)
			{
				throw new SQLException("Unable to connect to database", t);
			}
		}
	}
	
	public Client getClient()
	{
		return this.client;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Statement createStatement() throws SQLException
	{
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		return new ESStatement(this);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException
	{
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		return new ESPreparedStatement(this, sql);
	}

	@Override
	public CallableStatement prepareCall(String sql) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException
	{
		// TODO use params
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		return new ESStatement(this);
	}

	@Override
	public String nativeSQL(String sql) throws SQLException
	{
		return sql;
	}

	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException
	{
		this.autoCommit = autoCommit;
	}

	@Override
	public boolean getAutoCommit() throws SQLException
	{
		return autoCommit;
	}

	@Override
	public void commit() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void rollback() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void close() throws SQLException
	{
		if (isClosed())
			return;
		for (ESStatement st : this.statements)
			st.close();
		statements.clear();
		client.close();
		this.active = false;
	}

	@Override
	public boolean isClosed() throws SQLException
	{
		return !active;
	}

	@Override
	public DatabaseMetaData getMetaData() throws SQLException
	{
		HostPortPair hostPortPair = this.connInfo.getHosts().get(0);
		return new ESDatabaseMetaData(hostPortPair.getHost(), hostPortPair.getPort(), client, this.getClientInfo(), this);
//		return new ESDatabaseMetaData(this);
	}

	@Override
	public void setReadOnly(boolean readOnly) throws SQLException
	{
		this.readOnly = readOnly;
	}

	@Override
	public boolean isReadOnly() throws SQLException
	{
		return readOnly;
	}

	@Override
	public void setCatalog(String catalog) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public String getCatalog() throws SQLException
	{
		return null;
	}

	@Override
	public void setTransactionIsolation(int level) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public int getTransactionIsolation() throws SQLException
	{
		return ESConnection.TRANSACTION_NONE;
	}

	@Override
	public SQLWarning getWarnings() throws SQLException
	{
		return null;
	}

	@Override
	public void clearWarnings() throws SQLException
	{
		// TODO
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
			throws SQLException
	{
		// TODO use params?
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		return new ESPreparedStatement(this, sql);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Map<String, Class<?>> getTypeMap() throws SQLException
	{
		ResultSet rs = getMetaData().getColumns(null, null, null, null);
		Map<String, Map<String, Integer>> tableColumnInfo = new HashMap<String, Map<String, Integer>>();
		while (rs.next())
		{
			String table = rs.getString(3);
			String col = rs.getString(4);
			int type = rs.getInt(5);
			if (!tableColumnInfo.containsKey(table))
				tableColumnInfo.put(table, new HashMap<String, Integer>());
			tableColumnInfo.get(table).put(col, type);
		}
		this.connInfo.getProperties()
			.put(Utils.PROP_TABLE_COLUMN_MAP, tableColumnInfo);

		Map<String, Class<?>> result = new HashMap<String, Class<?>>();
		for (String type : tableColumnInfo.keySet())
		{
			for (String field : tableColumnInfo.get(type).keySet())
			{
				result.put(type + "." + field, Heading.getClassForTypeId(tableColumnInfo.get(type).get(field)));
			}
		}
		return result;
	}

	@Override
	public void setTypeMap(Map<String, Class<?>> map) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void setHoldability(int holdability) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public int getHoldability() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Savepoint setSavepoint() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Savepoint setSavepoint(String name) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void rollback(Savepoint savepoint) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void releaseSavepoint(Savepoint savepoint) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException
	{
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		if (isClosed())
			throw new SQLException("Connection closed");
		ESStatement st = new ESStatement(this);
		statements.add(st);
		return st;
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException
	{
		// TODO use params
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		if (isClosed())
			throw new SQLException("Connection closed");

		ESPreparedStatement st = new ESPreparedStatement(this, sql);
		statements.add(st);
		return st;
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException
	{
		// TODO use params
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		if (isClosed())
			throw new SQLException("Connection closed");

		ESPreparedStatement st = new ESPreparedStatement(this, sql);
		statements.add(st);
		return st;
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException
	{
		// TODO use params
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		if (isClosed())
			throw new SQLException("Connection closed");

		ESPreparedStatement st = new ESPreparedStatement(this, sql);
		statements.add(st);
		return st;
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException
	{
		// TODO use params
		if (this.client == null)
		{
			throw new SQLException("Unable to connect on specified schema '" + this.connInfo.getIndex() + "'");
		}
		if (isClosed())
			throw new SQLException("Connection closed");

		ESPreparedStatement st = new ESPreparedStatement(this, sql);
		statements.add(st);
		return st;
	}

	@Override
	public Clob createClob() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public Blob createBlob() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public NClob createNClob() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public SQLXML createSQLXML() throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public boolean isValid(int timeout) throws SQLException
	{
		return active;
	}

	@Override
	public void setClientInfo(String name, String value) throws SQLClientInfoException
	{
		this.connInfo.getProperties().setProperty(name, value);
	}

	@Override
	public void setClientInfo(Properties properties) throws SQLClientInfoException
	{
		this.connInfo.setProperties(properties);
	}

	@Override
	public String getClientInfo(String name) throws SQLException
	{
		return this.connInfo.getProperties().getProperty(name);
	}

	@Override
	public Properties getClientInfo() throws SQLException
	{
		return this.connInfo.getProperties();
	}

	@Override
	public Array createArrayOf(String typeName, Object[] elements) throws SQLException
	{
		return null;
	}

	@Override
	public Struct createStruct(String typeName, Object[] attributes) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void setSchema(String schema) throws SQLException
	{
		boolean indexExists = client.admin().indices().exists(new IndicesExistsRequest(schema)).actionGet().isExists();
		if (!indexExists)
			throw new SQLException("Index '" + schema + "' does not exist");
		this.connInfo.setIndex(schema);
	}

	@Override
	public String getSchema() throws SQLException
	{
		return this.connInfo.getIndex();
	}

	@Override
	public void abort(Executor executor) throws SQLException
	{
		throw new SQLFeatureNotSupportedException(Utils.getLoggingInfo());
	}

	@Override
	public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException
	{
		this.timeout = milliseconds;
	}

	@Override
	public int getNetworkTimeout() throws SQLException
	{
		return timeout;
	}

}

------ HostPortPair
package nl.anchormen.sql4es.model;

import java.sql.SQLException;

public class HostPortPair
{
	private String host;
	private int port;
	
	public HostPortPair(String host) throws SQLException
	{
		this(host, Utils.PORT);
	}
	
	public HostPortPair(String host, int port) throws SQLException
	{
		if(host == null || host.isEmpty() || port <= 0)
			throw new SQLException("Invalid URL, no host specified");
		this.host = host;
		this.port = port;
	}
	
	/**
	 * @return the host
	 */
	public String getHost()
	{
		return host;
	}
	/**
	 * @param host the host to set
	 */
	public void setHost(String host)
	{
		this.host = host;
	}
	
	/**
	 * @return the port
	 */
	public int getPort()
	{
		return port;
	}
	/**
	 * @param port the port to set
	 */
	public void setPort(int port)
	{
		this.port = port;
	}
	
	@Override
	public String toString()
	{
		return host+":"+port;
	}
	
	@Override
	public boolean equals(Object o)
	{
		if (o == this) return true;
		if (!(o instanceof HostPortPair)) return false;
		HostPortPair other = (HostPortPair) o;
		if (this.port != other.port) return false;
		if (this.host.equals(other.host)) 
			return false;
		return true;
	}
}

**Comment by corneversloot** [comment]
whow... you did an impressive amount of work on this! I do not really understand what 'mysql Load Balancing jdbc url style' means but it sounds like it would be a good addition for the driver. Can you make a pull request for this so i can review and test it?

**Comment by corneversloot** [comment]
No follow up
