### ISSUE TITLE
Cannot get nested of nested field correctly

### ISSUE THREAD

**Issue by kdh6429** [Anchormen/sql4es#7]
```
PUT /my_index
{
  "mappings": {
    "blogpost": {
      "properties": {
        "comments": {
          "type": "nested"
        }
      }
    }
  }
}



PUT /my_index/blogpost/1
{
  "title": "Nest eggs",
  "body":  "Making your money work...",
  "comments": [ 
    {
      "user":    { "id" : "John Smith"},
      "comment": "Great article"
    },
    {
      "user":    { "id" : "Alice White"},
      "comment": "More like this please"
    }
  ]
}

```

Here is sample data I made and queried like
`select * from blogpost where _id='1';`

It converted correctly as json query
```
GET /my_index/_search
{
   "size": 200,
   "timeout": 10000,
   "post_filter": {
      "ids": {
         "type": "blogpost",
         "values": [
            "1"
         ]
      }
   }
}

```

and return data is correct in ES BUT not in sql4es result table.

![image](https://cloud.githubusercontent.com/assets/6263966/14337698/3985779e-fcab-11e5-93f8-e936a72e8f77.png)

comments.user.id of second row should be "Alice White", but sql4es just filled out _**first** nested of nested data_ to _**all** nested of nested data_.

**Comment by corneversloot** [comment]
The current method that 'explodes' nested results as if they are joins does not take the nested object into account which I believe creates this result. I'll look into it.

You seem to be good at finding tough test cases, feel free to add some tests to the driver because the current ones clearly are not enough (especially not with nested types)

**Comment by kdh6429** [comment]
Since I'm new to ES, sql4es is best library for me :) 
I changed mappings to make sql4es understand it has nested of nested but still not work.
```
PUT /my_index
{
  "mappings": {
    "blogpost": {
      "properties": {
        "comments": {
          "type": "nested"
          "properties" : {
            "uers" : { 
              "type": "nested"
            }
          }
        }
      }
    }
  }
}
```

**Comment by corneversloot** [comment]
According to my tests your mapping with *nested-within-nested* should have worked. If this is the real mapping you applied the problem might be the typo in 'uers' (which should be users i guess).

I have added some tests to cover the nested-within-nested scenario which are all passed. You can try the latest release to see if it helps. Unfortunately i did not have enough time to test more elaborate queries with nested types so you might stumble upon more bugs in this area.

**Comment by kdh6429** [comment]
You are right. There was mis-typo. With lastest release, I checked this issued queries and worked well :)
