### ISSUE TITLE
Query with identical fields does not correctly populate the result set

### ISSUE THREAD

**Issue by acommendador** [Anchormen/sql4es#8]
Using 8.2.2 built from source (4/20/2016) and testing with SQL Workbench/J Build 119 and Elasticsearch 2.0.2/2.1.1/2.1.2 a query like "SELECT field as field_1, field as field_2, field as field_3 FROM table;" returns a result set with all three columns but only the last populated with values.

**Comment by corneversloot** [comment]
The driver does not yet support this type of queries simply because the mapping from document fields to the resultset was not designed with this scenario in mind. I will see if i can add it to the driver and let you know how it goes.

**Comment by corneversloot** [comment]
I have put this issue on the backlog but I have very little time for this atm. Ill close this issue for now.
